---
- name: Installation
  hosts: localhost
  
  tasks:
  
  - name: Installation 
    apt:
      name: "{{item.a}}"
      state: "{{item.b}}"
      update_cache: "{{item.c}}"
    with_items:
      - {a: git, b: present, c: no}
      - {a: maven, b: latest, c: no}
      - {a: tomcat9, b: present, c: no}
 
  - name: maven build
    #command: bash -lc "mvn clean --file $pwd/*.pom && mvn compile --file *.pom && mvn package --file *.pom && cp target/java-tomcat-maven-example.war /var/lib/tomcat9/webapps"
    #command: chdir /var/lib/jenkins/workspace/jenkins-ansible-maven-sample-project/jenkins-ansible-maven-sample-project ls
    command: bash -lc "mvn clean --file /var/lib/jenkins/workspace/jenkins-ansible-maven-sample-project/jenkins-ansible-maven-sample-project/pom.xml"
  - name: Restart tomcat9
    service:
     name: tomcat9
     state: restarted
...  
