---
- name: Installation
  hosts: localhost
  tasks:
  - name: Installation 
    apt:
      name: "{{item.a}}"
      state: "{{item.b}}"
      update_cache: "{{item.c}}"
    with_items:
      - {a: git, b: present, c: no}
      - {a: maven, b: latest, c: no}
      - {a: tomcat9, b: present, c: no}
      - {a: tomcat9-admin, b: present, c: no}                   
  - name: maven build
    command: bash -lc "cd /var/lib/jenkins/workspace/jenkins-ansible-maven-sample-project/jenkins-ansible-maven-sample-project && mvn clean && mvn compile && mvn package && cp target/java-tomcat-maven-example.war /var/lib/tomcat9/webapps"
  - name: Restart tomcat9
    service:
     name: tomcat9
     state: restarted
     
     
- name: Installation for webservers
  hosts: webservers
  tasks:
  - name: Installation for other servers
    apt:
      name: "{{item.a}}"
      state: "{{item.b}}"
      update_cache: "{{item.c}}"
    with_items:
      - {a: git, b: present, c: no}
      - {a: maven, b: latest, c: no}
      - {a: tomcat9, b: present, c: no}
      - {a: tomcat9-admin, b: present, c: no}   
 
  - name: copying index.xml,web.xml & pom.xml files to manage nodes
    copy:
       src: /var/lib/jenkins/workspace/jenkins-ansible-maven-sample-project/jenkins-ansible-maven-sample-project/src/main/webapp/index.jsp
       dest: /root/src/main/webapp/index.jsp
       src: /var/lib/jenkins/workspace/jenkins-ansible-maven-sample-project/jenkins-ansible-maven-sample-project/src/main/webapp/WEB-INF/web.xml
       dest: /root/src/main/webapp//WEB-INF/web.xml       
       src: /var/lib/jenkins/workspace/jenkins-ansible-maven-sample-project/jenkins-ansible-maven-sample-project/pom.xml
       dest: /root/pom.xml
  - name: maven build
    command: bash -lc "cd /root && mvn clean && mvn compile && mvn package && cp target/java-tomcat-maven-example.war /var/lib/tomcat9/webapps"
  - name: Restart tomcat9
    service:
     name: tomcat9
     state: restarted
...  
