---
- name: Installation
 
  hosts: all
  
  tasks:
  
  - name: Update APT Cache
  apt:
    update_cache: yes
    force_apt_get: yes

- name: Remove apt lock file
  file:
    state: absent
    path: "/var/lib/dpkg/lock"

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    force_apt_get: yes
    
  
  - name: Installation git maven tomcat
    apt:
      name: "{{item.a}}"
      state: "{{item.b}}"
      update_cache: "{{item.c}}"
    with_items:
      - {a: git, b: present, c: no}
      - {a: maven, b: latest, c: no}
      - {a: tomcat9, b: present, c: no}
 
  - name: maven build
    command: bash -lc "mvn clean && mvn compile && mvn package && cp target/java-tomcat-maven-example.war /var/lib/tomcat9/webapps"
  - name: Restart tomcat9
    service:
     name: tomcat9
     state: restarted
...  
